Verifying: test/files/anchor1.md
test/files/anchor1.md: Can't find section '#Overview' in test/files/anchor1.md
test/files/anchor1.md: Can't find section '#Overview' in test/files/anchor2.md
Verifying: test/files/anchor2.md
Verifying: test/files/dir.md
Verifying: test/files/dir/subfile1.md
test/files/dir/subfile1.md: Can't find: test/files/dir/../badlink.md
Verifying: test/files/empty.md
Verifying: test/files/missingmd.md
test/files/missingmd.md: Can't find: test/files/nofile.md
Verifying: test/files/nolinks.md
Verifying: test/files/numend1.md
Verifying: test/files/numend2.md
Verifying: test/files/oneliner.md
Verifying: test/files/simple.md
test/files/simple.md: Can't find: test/files/link1.md
test/files/simple.md: Can't find: test/files/link2.md
test/files/simple.md: Can't find: test/files/bmark1
test/files/simple.md: Can't find: test/files/link3.md
Verifying: test/files/specials1.md
test/files/specials1.md: Can't find section '#yours' in test/files/specials1.md
Verifying: test/files/specials2.md
Verifying: test/files/split2.md
test/files/split2.md: Can't find: test/files/badlink5.md
Verifying: test/files/split3.md
Verifying: test/files/split.md
Verifying: test/files/unclosed.md
